spring:
  datasource:
    min-idle: 5
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    max-wait: 10000
    url: jdbc:mysql://47.115.41.15:3308/adam?useUnicode=true&characterEncoding=UTF8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
    max-idle: 10
    test-on-borrow: false
    password: adam-5r532p
    initial-size: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: adam-app
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    # 自定义404
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    #不要为我们工程中的资源文件建立映射
    add-mappings: false


#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义API URI 前缀 本机测试有效
server:
  servlet:
    context-path: /demo
  port: 8080

# 是否开启swagger
swagger:
  show: true