FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
VOLUME /data/logs
VOLUME /data/aaron
ADD springbootdocker-1.0.0-SNAPSHOT.jar app.jar
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Dspring.profiles.active=dev -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]









